// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "shadcnComponents": {
    "breadcrumb": {
      "navLabel": "Breadcrumb",
      "more": "More"
    },
    "carousel": {
      "nextSlide": "Next slide",
      "previousSlide": "Previous slide",
      "carouselLabel": "Carousel"
    },
    "dialog": {
      "close": "Close"
    },
    "command": {
      "title": "Command palette",
      "description": "Search for a command to run..."
    },
    "pagination": {
      "navLabel": "Pagination",
      "previousPage": "Previous",
      "nextPage": "Next",
      "goToPreviousPage": "Go to previous page",
      "goToNextPage": "Go to next page",
      "morePages": "More pages"
    },
    "sheet": {
      "close": "Close"
    }
  },
  "customComponents": {
    "themeSwitch": {
      "label": "Choose a theme",
      "placeholder": "Theme",
      "light": "Light",
      "dark": "Dark",
      "system": "System"
    }
  },
  "landingPage": {
    "metadata": {
      "description": "Professional full-stack starter for building SaaS applications."
    },
    "welcome": "Welcome to the {name} page!"
  },
  "blog": {
    "metadata": {
      "title": "Blog",
      "description": "Notes and updates from SaaSy Land."
    },
    "nav": {
      "docs": "Docs",
      "blog": "Blog"
    },
    "index": {
      "title": "Blog",
      "description": "Markdown posts compiled with Fumadocs MDX."
    },
    "post": {
      "backToBlog": "Back to blog",
      "writtenBy": "Written by",
      "dateLabel": "Published"
    }
  },
  "custom": {
    "about": {
      "sectionHeader": "Profile & Background",
      "location": "Location",
      "krakow": "Krakow, PL",
      "education": "Education",
      "degree": "BSc (Hons) CompSci",
      "university": "Durham University, UK",
      "experience": "Experience",
      "years": "5+ Years",
      "company": "Currently at IBM",
      "codebases": "Codebases",
      "network": "Network",
      "title": "<line1>ENGINEERING</line1><line2>MISSION-CRITICAL</line2><line3>SOLUTIONS.</line3>",
      "description": "As a Full Stack Engineer at <strong>IBM</strong>, I architect high-frequency systems where reliability and precision are non-negotiable. My work on the Financial Transaction Manager (FTM) involves navigating the complexities of enterprise-grade infrastructure to deliver resilient, scalable software.",
      "backgroundTitle": "01 / Background",
      "backgroundText": "My technical foundation was established at <strong>Durham University</strong> (UK) with a BSc in Computer Science. Since then, I have focused on mastering the modern web ecosystem, bridging the gap between complex academic theory and the delivery of robust, production-grade systems.",
      "expertiseTitle": "02 / Expertise",
      "expertiseText": "While I specialize in the JS/TS ecosystem (<strong>React, Next.js, TanStack</strong>), I maintain a language-agnostic approach to system design. I frequently leverage Go for high-throughput microservice, ensuring optimal performance and long-term maintainability.",
      "quote": "\"Modern web architecture demands more than just functionality. I prioritize performance as a core feature, specializing in optimizing the critical path—from database indexing to edge-side rendering—to deliver millisecond-level responsiveness at scale\"",
      "coreTechnologies": "Core Technologies"
    },
    "philosophy": {
      "methodology": "Methodology",
      "engineeringStandards": "ENGINEERING <span>STANDARDS</span>",
      "scrollExplore": "Scroll to Explore",
      "buildingForTomorrow": "BUILDING FOR <br></br> <span>TOMORROW.</span>",
      "buildingDesc": "Modern web development isn't just about writing code. It's also about managing of complexity. I focus on orchestrating resilient systems and modular architectures that remain performant, maintainable, and adaptable as they grow.",
      "card1Title": "Simplicity",
      "card1Desc": "Complexity is a tax on velocity. I prioritize lean architectures and modular design to strip away non-essential abstractions, ensuring the system remains robust and easy to reason about.",
      "card2Title": "Performance",
      "card2Desc": "Performance is a fundamental requirement. From optimized data-fetching strategies with TanStack to efficient server-side rendering, I engineer for millisecond-level responsiveness across the entire critical path.",
      "card3Title": "Scalability",
      "card3Desc": "Designing for the future requires decoupled, event-driven patterns and a strict separation of concerns. I build systems that scale horizontally without compromising on developer velocity or structural integrity.",
      "card4Title": "User-Centric",
      "card4Desc": "Technical decisions are ultimately measured by their impact on the end-user. I ensure high availability and predictable system behavior through rigorous type-safety, comprehensive testing, and proactive monitoring."
    },
    "hero": {
      "available": "COMMITTED TO ARCHITECTURAL EXCELLENCE",
      "basedIn": "Based in Krakow, PL",
      "full": "FULL",
      "specialized": "(01) — SPECIALIZING IN HIGH-PERFORMANCE FULL-STACK ARCHITECTURES",
      "stack": "STACK",
      "developer": "DEVELOPER",
      "building": "Designing and delivering high-performance, full-stack systems with a focus on <strong>scalability</strong> and <strong>architectural integrity</strong>.",
      "viewWork": "View Work",
      "contactMe": "Contact Me"
    },
    "skills": {
      "proficiency": "Proficiency",
      "toolkit": "A COMPREHENSIVE TOOLKIT FOR <br></br><span>COMPLEX CHALLENGES.</span>",
      "fullStack": "Full Stack / Cloud Native",
      "eventSourcing": "Event Sourcing",
      "cqrs": "CQRS",
      "cleanArchitecture": "Clean Architecture",
      "ddd": "DDD",
      "tdd": "TDD/BDD",
      "microFrontends": "Micro-Frontends",
      "graphql": "GraphQL",
      "wasm": "WASM",
      "feArch": "Frontend Systems Design",
      "feArchDesc": "Engineering high-performance web applications with a focus on modularity and state-synchronization. Expertise in advanced rendering patterns (ISR/SSR), efficient data-fetching strategies with TanStack, and building scalable component systems for enterprise-grade products.",
      "beSystems": "Scalable Backend Infrastructure",
      "beSystemsDesc": "Designing resilient, high-throughput backend services using Go and Node.js. Focused on database optimization, cache invalidation strategies, and containerized orchestration to ensure 99.9% availability and low-latency data processing at scale.",
      "strategy": "Technical Strategy & Leadership",
      "strategyDesc": "Bridging the gap between business objectives and technical execution. I specialize in architecting technical roadmaps, enforcing high engineering standards through rigorous code reviews, and mentoring cross-functional teams to deliver production-grade software."
    },
    "work": {
      "selected": "Selected Projects (0{count})",
      "readCaseStudy": "Read Case Study"
    },
    "insights": {
      "title": "INSIGHTS.",
      "subtitle": "Engineering Thoughts",
      "readArticle": "Read Article",
      "viewArchive": "View More Articles"
    },
    "contact": {
      "start": "GET IN TOUCH",
      "interested": "Always open to discussing architectural challenges, technical leadership, or high-impact engineering opportunities. Whether it’s a deep dive into system design or a future collaboration, my door is always open.",
      "email": "Email",
      "hello": "Hello, my name is",
      "andFrom": "and I'm from",
      "partner": "I'd like to discuss",
      "reachMe": "You can reach me at",
      "discuss": "to start the conversation.",
      "placeholderName": "YOUR NAME",
      "placeholderCompany": "ORGANIZATION",
      "placeholderProject": "WHAT WOULD YOU LIKE TO DISCUSS?",
      "placeholderEmail": "EMAIL ADDRESS",
      "send": "SEND MESSAGE",
      "sending": "Sending message...",
      "success": "Message sent successfully! I'll get back to you soon.",
      "error": "Failed to send message. Please try again later.",
      "nameRequired": "Name is required",
      "emailRequired": "Valid email is required",
      "detailsRequired": "Please provide some details",
      "copyright": "© 2024 PJBorowiecki Systems",
      "location": "Krakow, PL"
    },
    "modal": {
      "close": "Close",
      "role": "Role",
      "lead": "Lead Engineer",
      "year": "Year",
      "category": "Category",
      "brief": "The Brief",
      "architectural": "Architectural Decisions",
      "results": "Results.",
      "uptime": "Uptime",
      "latency": "Latency",
      "nextProject": "Next Project",
      "comingSoon": "Coming Soon"
    },
    "navbar": {
      "letsTalk": "Let's Talk"
    },
    "dashboard": {
      "header": {
        "acmeCorp": "Acme Corp",
        "projects": "Projects",
        "mobileAppRedesign": "Mobile App Redesign",
        "share": "Share",
        "newIssue": "New Issue"
      },
      "sidebar": {
        "acmeCorp": "Acme Corp",
        "newIssue": "New Issue",
        "search": "Search...",
        "inbox": "Inbox",
        "myIssues": "My Issues",
        "projects": "Projects",
        "views": "Views",
        "yourTeams": "Your Teams",
        "coreEngineering": "Core Engineering",
        "designSystems": "Design Systems",
        "alexDesigner": "Alex Designer"
      },
      "project": {
        "title": "Mobile App Redesign",
        "desc": "Comprehensive overhaul of the iOS and Android application navigation structure, aiming for 20% faster task completion times.",
        "mobileTeam": "Mobile Team",
        "target": "Target: Oct 30",
        "onTrack": "On Track",
        "completed": "Completed",
        "issuesDone": "24 of 33 issues done",
        "overview": "Overview",
        "issues": "Issues",
        "cycles": "Cycles",
        "documents": "Documents",
        "about": "About",
        "edit": "Edit",
        "aboutText": "This project aims to modernize the mobile application experience. The current navigation stack is legacy-based and causes performance bottlenecks on older Android devices.",
        "keyObjectives": "Key Objectives:",
        "obj1": "Migrate from Activity-based navigation to Fragment-based.",
        "obj2": "Implement new \"Fluid Motion\" design language.",
        "obj3": "Reduce app startup time by 200ms.",
        "obj4": "Achieve 99.9% crash-free sessions on iOS 15+.",
        "recentActivity": "Recent Activity",
        "sarah": "Sarah",
        "marked": "marked",
        "asComplete": "as complete",
        "ago2h": "2 hours ago",
        "alexDesigner": "Alex Designer",
        "uploaded": "uploaded 4 new designs to",
        "figma": "Figma",
        "yesterday": "Yesterday at 4:30 PM",
        "felix": "Felix",
        "createdIssue": "created issue",
        "oct24": "Oct 24",
        "projectLead": "Project Lead",
        "cycle": "Cycle",
        "cycle24": "Cycle 24",
        "daysLeft": "12 days left",
        "resources": "Resources",
        "designSystem": "Design System",
        "repo": "Repo: acme-mobile",
        "productSpec": "Product Spec",
        "milestones": "Milestones",
        "conceptValidation": "Concept Validation",
        "completedOct10": "Completed Oct 10",
        "betaRelease": "Beta Release",
        "dueOct28": "Due Oct 28",
        "publicLaunch": "Public Launch",
        "nov15": "Nov 15"
      }
    }
  },
  "emails": {
    "contact": {
      "title": "New Contact Form Submission",
      "preview": "New message from {name}",
      "name": "Name:",
      "email": "Email:",
      "company": "Company:",
      "details": "Details"
    }
  }
};
export default messages;